### ISSUE TITLE
PATH invalide mais le script continu

### ISSUE THREAD

**Issue by GlaceCoding** [AudeizReading/virtual-campus-42nice#13]
Quand on a `Invalid path` il faudrait quitter le script

https://github.com/AudeizReading/virtual-campus-42nice/blob/abe229f0f7da8a000c58c59f52fdfffe203616ac/configure.sh#L128-L133

**Comment by GlaceCoding** [comment]
Il faudrait probablement proposer de mkdir le path indiqué s'il n'existe pas

**Comment by AudeizReading** [comment]
C'est voulu, pour le moment, que le script continue meme si le path est invalide. Ca ne va juste pas connecter de volumes au container, et démarrer le container sur `/usr/src`. Le path invalide peut etre du à une erreur de saisie de l'utilisateur.

Ca me ferait agir sur la machine de l'hote, de proposer un mkdir, je voudrais eviter au maximum ce genre de manip. L'idee c'est de pouvoir connecter un travail deja existant (meme si c'est juste le folder sans contenu). Cela m'assure la volonté et l'accord de l'utilisateur d'interagir sur cette section du disque.
Il faudrait que j'etudie plus en profondeur la possibilité de mkdir sur la machine hote, car cela implique + de vérifications, s'assurer qu'il sagit d'une volonté réelle de créer un nouveau répertoire et pas d'une erreur de saisie + qu'on puisse pas reproduire en mode defense, et s'assurer qu'on cree pas n'importe quoi, etc.

C'est pas vraiment une issue, car ce comportement est indiqué dans le README.md, par contre je laisse ouvert car je reconnais que l'interet n'est pas grand de juste pouvoir entrer dans le container.

**Comment by AudeizReading** [comment]
Pour le moment, oui, si on se trompe et qu'on veut connecter un travail, il faut tout recommencer avec `make uninstall` && `make install`.

Faudrait que je parcourre l'historique (parce que ca pourrait expliquer pourquoi j'ai suivi cette voie precisément). À vrai dire je ne me souviens plus de ce que j'ai pu me dire pour justifier de laisser ca comme ca. Sans doute de pouvoir laisser malgré tout l'accès à un environnement Ubuntu meme si on peut rien y sauvegarder. Il me semble qu'au départ, je n'avais pas envisagé de connecter des volumes, l'idée c'etait juste de pouvoir corriger un projet.

Ta remarque est très pertinente et sera étudiée, car comme je te l'expliquais, il n'est pas juste question de laisser pouvoir `mkdir` un repertoire inexistant.

**Comment by AudeizReading** [comment]
C'est patché! #22 
On ne peut juste pas encore créer de nouveau répertoires, par contre, on n'a maintenant la possibilité de quitter si le path est invalide.
Un controle sur l'etat de Docker et des containers a aussi été renforcé
